'use client';

import Link from 'next/link';
import { ArrowLeft, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Lightbulb, Send } from 'lucide-react';
import { useMemo, useState } from 'react';
import { cn } from '@/lib/utils';
import { getPartDescription, partLabels, ReadingLesson } from '@/lib/reading-data';

export default function ReadingExercise({ lesson }: { lesson: ReadingLesson }) {
  const [current, setCurrent] = useState(0);
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [checked, setChecked] = useState(false);
  const question = lesson.questions[current];
  const answered = Object.keys(answers).length;
  const progress = Math.round((answered / lesson.questions.length) * 100);
  const setAnswer = (answer: string) => { setAnswers((value) => ({ ...value, [question.id]: answer })); setChecked(false); };
  const go = (direction: number) => { setCurrent((value) => Math.max(0, Math.min(lesson.questions.length - 1, value + direction))); setChecked(false); };
  const result = useMemo(() => checked && answers[question.id] === question.answer, [answers, checked, question]);

  return <main className='min-h-full bg-muted-background p-4 text-foreground md:p-8'>
    <div className='mx-auto flex max-w-6xl flex-col gap-6'>
      <header className='flex items-center justify-between gap-4'><Link href='/reading' className='flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground'><ArrowLeft className='size-4' /> Thư viện Reading</Link><div className='flex items-center gap-2 rounded-full bg-card px-3 py-2 text-xs font-medium text-muted-foreground'><Clock3 className='size-3.5' /> {lesson.duration} phút</div></header>
      <section className='rounded-2xl border bg-card p-5 shadow-sm md:p-7'><div className='flex flex-col gap-4 md:flex-row md:items-start md:justify-between'><div><div className='flex flex-wrap items-center gap-2'><span className='rounded-md bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary'>{partLabels[lesson.part]}</span><span className='rounded-md bg-secondary px-2.5 py-1 text-xs text-muted-foreground'>{lesson.difficulty}</span></div><h1 className='mt-4 text-2xl font-bold tracking-tight md:text-3xl'>{lesson.title}</h1><p className='mt-2 text-sm text-muted-foreground'>{getPartDescription(lesson.part)} · {lesson.questions.length} câu hỏi</p></div><div className='w-full md:max-w-48'><div className='mb-2 flex justify-between text-xs text-muted-foreground'><span>Tiến độ</span><span>{progress}%</span></div><div className='h-2 overflow-hidden rounded-full bg-secondary'><div className='h-full rounded-full bg-primary transition-all' style={{ width: `${progress}%` }} /></div></div></div></section>
      <div className='grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]'>
        <section className='flex flex-col gap-5'>
          {lesson.passage && <article className='whitespace-pre-line rounded-xl border bg-card p-5 text-sm leading-7 shadow-sm md:p-7'><p className='mb-4 text-xs font-bold uppercase tracking-[0.15em] text-primary'>Reading passage</p>{lesson.passage}</article>}
          <article className='rounded-xl border bg-card p-5 shadow-sm md:p-7'><div className='flex items-start justify-between gap-4'><div><p className='text-sm font-semibold text-primary'>Câu {question.id}</p><h2 className='mt-3 text-lg font-semibold leading-7'>{question.prompt}</h2></div><span className='rounded-full bg-secondary px-3 py-1 text-xs text-muted-foreground'>{current + 1}/{lesson.questions.length}</span></div>{lesson.part === 'part-6' && <div className='mt-6 rounded-lg border border-dashed bg-secondary/50 p-4 text-sm leading-7 text-muted-foreground'>Chọn từ phù hợp để hoàn chỉnh nội dung email ở trên.</div>}{question.options ? <div className='mt-7 grid gap-3'>{question.options.map((option, index) => <button key={option} onClick={() => setAnswer(option)} className={cn('flex items-center gap-3 rounded-xl border p-4 text-left text-sm transition-colors', answers[question.id] === option ? 'border-primary bg-primary/10 text-foreground' : 'hover:bg-secondary')}><span className='flex size-7 shrink-0 items-center justify-center rounded-full bg-secondary font-semibold text-muted-foreground'>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div> : <textarea value={answers[question.id] ?? ''} onChange={(event) => setAnswer(event.target.value)} placeholder='Nhập câu trả lời của bạn...' className='mt-7 min-h-28 w-full resize-y rounded-xl border bg-background p-4 text-sm outline-none focus:ring-2 focus:ring-primary/30' />}{checked && <div className={cn('mt-5 flex items-center gap-2 rounded-lg p-3 text-sm', result ? 'bg-primary/10 text-primary' : 'bg-destructive/10 text-destructive')}><CheckCircle2 className='size-4' />{result ? 'Chính xác! Bạn đang làm rất tốt.' : `Đáp án tham khảo: ${question.answer}`}</div>}<div className='mt-7 flex flex-wrap items-center justify-between gap-3 border-t pt-5'><button onClick={() => go(-1)} disabled={current === 0} className='inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm disabled:opacity-40'><ChevronLeft className='size-4' /> Câu trước</button><button onClick={() => setChecked(true)} disabled={!answers[question.id]} className='inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-40'><Send className='size-4' /> Kiểm tra</button><button onClick={() => go(1)} disabled={current === lesson.questions.length - 1} className='inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm disabled:opacity-40'>Câu tiếp <ChevronRight className='size-4' /></button></div></article>
        </section>
        <aside className='flex flex-col gap-4'><div className='rounded-xl border bg-card p-5 shadow-sm'><div className='flex items-center gap-2 font-semibold'><Lightbulb className='size-4 text-primary' /> Mẹo làm bài</div><p className='mt-3 text-sm leading-6 text-muted-foreground'>{lesson.part === 'part-5' ? 'Đọc toàn bộ câu trước khi nhìn đáp án. Xác định từ loại cần điền để loại nhanh các lựa chọn.' : lesson.part === 'part-6' ? 'Đọc cả đoạn để nắm mạch ý. Đừng chỉ dựa vào một câu ngay trước chỗ trống.' : 'Đọc câu hỏi trước, sau đó quay lại passage để tìm từ khóa và thông tin liên quan.'}</p></div><div className='rounded-xl border bg-card p-5 shadow-sm'><p className='text-sm font-semibold'>Câu hỏi</p><div className='mt-4 grid grid-cols-5 gap-2'>{lesson.questions.map((item, index) => <button key={item.id} onClick={() => setCurrent(index)} className={cn('size-9 rounded-lg border text-xs font-semibold', current === index ? 'border-primary bg-primary text-primary-foreground' : answers[item.id] ? 'border-primary/40 bg-primary/10 text-primary' : 'bg-background text-muted-foreground')}>{item.id}</button>)}</div></div></aside>
      </div>
    </div>
  </main>;
}
