export type SpeakingType = 'warm-up' | 'read-aloud' | 'describe' | 'opinion' | 'shadowing' | 'q-and-a';
export type SpeakingDifficulty = 'Dễ' | 'Trung bình' | 'Khó';
export type SpeakingLesson = { slug: string; type: SpeakingType; title: string; subtitle: string; difficulty: SpeakingDifficulty; duration: number; prompt: string; hint: string; modelAnswer: string; image?: string };
export const speakingTypes: Array<SpeakingType | 'all'> = ['all', 'describe', 'q-and-a', 'read-aloud', 'shadowing'];
export const speakingTypeLabels: Record<SpeakingType | 'all', string> = { all: 'Tất cả dạng bài', describe: 'Mô tả tranh', 'q-and-a': 'Trả lời câu hỏi', 'read-aloud': 'Đọc câu', shadowing: 'Nói nhại', 'warm-up': 'Khởi động', opinion: 'Trình bày ý kiến' };
export const speakingDifficulties: Array<SpeakingDifficulty | 'all'> = ['all', 'Dễ', 'Trung bình', 'Khó'];
export const speakingLessons: SpeakingLesson[] = [
 { slug: 'introduce-your-routine', type: 'warm-up', title: 'Introduce your daily routine', subtitle: 'Luyện phản xạ với câu hỏi quen thuộc về thói quen mỗi ngày.', difficulty: 'Dễ', duration: 3, prompt: 'Tell us about your typical weekday routine.', hint: 'Mở đầu bằng thời gian thức dậy, sau đó nói về công việc và buổi tối.', modelAnswer: 'On a typical weekday, I wake up at six thirty and prepare a quick breakfast. I work until late afternoon, then I usually go for a walk before having dinner with my family.' },
 { slug: 'office-announcement', type: 'read-aloud', title: 'Office announcement', subtitle: 'Đọc to một thông báo ngắn, tập trung vào trọng âm và ngắt câu.', difficulty: 'Trung bình', duration: 4, prompt: 'Please read the announcement below clearly and naturally: The third-floor meeting room will be unavailable this afternoon due to maintenance.', hint: 'Nhấn vào unavailable, this afternoon và maintenance.', modelAnswer: 'Please read the announcement with a clear pace and a short pause after afternoon.' },
 { slug: 'answer-customer-question', type: 'q-and-a', title: 'Answer a customer question', subtitle: 'Đọc câu hỏi, chuẩn bị ý và trả lời như đang tư vấn khách hàng.', difficulty: 'Dễ', duration: 4, prompt: 'A customer asks: “Could you explain how I can change my delivery address?” Answer politely and give two clear steps.', hint: 'Bắt đầu bằng lời xác nhận, sau đó dùng first/then để trình bày hai bước.', modelAnswer: 'Of course. First, open your order details and select the delivery address. Then, enter the new address and save the changes before the order is shipped.' },
 { slug: 'repeat-the-sentence', type: 'shadowing', title: 'Repeat the sentence', subtitle: 'Nghe câu mẫu, bắt chước nhịp điệu và nói lại thật tự nhiên.', difficulty: 'Dễ', duration: 3, prompt: 'Listen to the model sentence, then repeat it with the same rhythm: “I would be happy to send you the updated schedule by this afternoon.”', hint: 'Nghe một lần để hiểu ý, lần hai tập trung vào nối âm và nhấn updated schedule.', modelAnswer: 'I would be happy to send you the updated schedule by this afternoon.' },
 { slug: 'describe-a-team-meeting', type: 'describe', title: 'Describe a team meeting', subtitle: 'Quan sát bối cảnh và mô tả người, hành động cùng không gian.', difficulty: 'Trung bình', duration: 5, prompt: 'Describe a team meeting in an office. Mention the people, their actions, and the atmosphere.', hint: 'Sử dụng there is/there are và hiện tại tiếp diễn.', modelAnswer: 'Several colleagues are sitting around a table in a bright meeting room. One woman is presenting a chart while the others are listening and taking notes. The atmosphere seems focused but friendly.', image: '/images/speaking-team-meeting.png' },
 { slug: 'remote-work-opinion', type: 'opinion', title: 'Is remote work effective?', subtitle: 'Trình bày quan điểm trong 45 giây với lý do và ví dụ cụ thể.', difficulty: 'Khó', duration: 6, prompt: 'Do you think remote work is more effective than working in an office? Explain your opinion.', hint: 'Nêu quan điểm, hai lý do, rồi kết luận ngắn.', modelAnswer: 'I think remote work can be very effective because it saves commuting time and gives employees a quieter environment. However, teams need regular meetings and clear communication to stay connected.' },
 { slug: 'weekend-plans', type: 'warm-up', title: 'Plans for the weekend', subtitle: 'Trả lời câu hỏi cá nhân bằng câu đầy đủ và tự nhiên.', difficulty: 'Dễ', duration: 3, prompt: 'What are you planning to do this weekend?', hint: 'Dùng be going to hoặc plan to để nói về dự định.', modelAnswer: 'This weekend, I am planning to visit a new coffee shop with a friend. If the weather is nice, we are also going to walk around the city center.' },
 { slug: 'product-presentation', type: 'opinion', title: 'Present a new product', subtitle: 'Luyện nói có cấu trúc như một phần thuyết trình ngắn.', difficulty: 'Khó', duration: 7, prompt: 'Present a new productivity app to a group of customers.', hint: 'Giới thiệu sản phẩm, lợi ích chính và lời mời dùng thử.', modelAnswer: 'Today I would like to introduce a simple productivity app designed for busy teams. It helps users organize tasks, share updates, and keep deadlines visible in one place.' },
];
export const getSpeakingLesson = (slug: string) => speakingLessons.find((lesson) => lesson.slug === slug); 
export const speakingWave = [18, 28, 42, 22, 54, 34, 64, 30, 48, 24, 58, 36, 72, 30, 50, 26, 62, 38, 44, 20, 56, 32, 68, 26, 48, 22, 58, 34, 70, 30, 52, 24];
export const speakingAudioSample = 'https://cdn.pixabay.com/audio/2022/03/15/audio_6b7f5f61b1.mp3';
