export type WritingType = 'email' | 'response' | 'description' | 'chart' | 'opinion';
export type WritingDifficulty = 'Dễ' | 'Trung bình' | 'Khó';
export type WritingLesson = { slug:string; type:WritingType; title:string; subtitle:string; difficulty:WritingDifficulty; targetWords:number; prompt:string; keywords:string[]; rubric:string[]; chart?: { label:string; value:number }[] };
export const writingTypeLabels: Record<WritingType|'all',string> = { all:'Tất cả dạng bài', email:'Email công việc', response:'Phản hồi ngắn', description:'Mô tả đoạn văn', chart:'Mô tả biểu đồ', opinion:'Trình bày ý kiến' };
export const writingTypes: (WritingType|'all')[] = ['all','email','response','description','chart','opinion'];
export const writingDifficulties: (WritingDifficulty|'all')[] = ['all','Dễ','Trung bình','Khó'];
export const writingLessons: WritingLesson[] = [
 {slug:'reschedule-a-meeting',type:'email',title:'Reschedule a meeting',subtitle:'Viết email lịch sự để đề xuất thời gian họp mới.',difficulty:'Dễ',targetWords:80,prompt:'You need to reschedule tomorrow’s meeting because of a client call. Write an email to your colleague and suggest two alternative times.',keywords:['unfortunately','available','alternative','confirm'],rubric:['Đủ lý do và thời gian thay thế','Giọng văn lịch sự','Bố cục email rõ ràng']},
 {slug:'reply-to-a-request',type:'response',title:'Reply to a request',subtitle:'Trả lời một yêu cầu trong môi trường công sở.',difficulty:'Dễ',targetWords:60,prompt:'Your teammate asks you to share the latest sales file. Reply with a helpful, concise message and mention when you can send it.',keywords:['sure','latest version','by the end of','let me know'],rubric:['Trả lời trực tiếp yêu cầu','Thông tin thời hạn cụ thể','Câu văn tự nhiên']},
 {slug:'describe-a-workspace',type:'description',title:'Describe a workspace',subtitle:'Mô tả không gian, đồ vật và hoạt động bằng câu rõ ràng.',difficulty:'Trung bình',targetWords:100,prompt:'Describe a modern coworking space. Mention the layout, the people, and what they are doing.',keywords:['on the left','nearby','there is','are working'],rubric:['Mô tả đủ không gian','Dùng giới từ chính xác','Kết hợp hiện tại đơn và tiếp diễn']},
 {slug:'describe-a-sales-chart',type:'chart',title:'Describe a sales chart',subtitle:'Tóm tắt xu hướng, điểm cao thấp và so sánh số liệu.',difficulty:'Trung bình',targetWords:120,prompt:'Summarize the chart below for a short business report. Highlight the overall trend, the highest month, and one comparison.',keywords:['increased steadily','peaked at','compared with','by contrast'],rubric:['Nêu xu hướng chính','So sánh số liệu hợp lý','Dùng từ vựng mô tả biểu đồ'],chart:[{label:'Jan',value:42},{label:'Feb',value:55},{label:'Mar',value:51},{label:'Apr',value:73},{label:'May',value:68},{label:'Jun',value:86}]},
 {slug:'remote-work-opinion',type:'opinion',title:'Is remote work effective?',subtitle:'Trình bày quan điểm và bảo vệ bằng hai lý do.',difficulty:'Khó',targetWords:150,prompt:'Do you think remote work is effective for most teams? State your opinion and support it with two reasons and one example.',keywords:['in my view','firstly','for example','however'],rubric:['Quan điểm rõ ràng','Lập luận có liên kết','Ví dụ thuyết phục']},
];
export const getWritingLesson = (slug:string) => writingLessons.find((lesson) => lesson.slug === slug);
export const countWords = (value:string) => value.trim() ? value.trim().split(/\s+/).length : 0;
