'use client';
import Link from 'next/link';
import { ArrowRight, Clock3, Mic2, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import { cn } from '@/lib/utils';
import { speakingDifficulties, speakingLessons, speakingTypes, speakingTypeLabels, SpeakingDifficulty, SpeakingType } from '@/lib/speaking-data';
export default function SpeakingLibrary() {
 const [type, setType] = useState<SpeakingType | 'all'>('all'); const [difficulty, setDifficulty] = useState<SpeakingDifficulty | 'all'>('all'); const [page, setPage] = useState(1); const filtered = useMemo(() => speakingLessons.filter((x) => (type === 'all' || x.type === type) && (difficulty === 'all' || x.difficulty === difficulty)), [type, difficulty]); const pages = Math.max(1, Math.ceil(filtered.length / 4)); const visible = filtered.slice((page - 1) * 4, page * 4); const choose = (next: SpeakingType | 'all') => { setType(next); setPage(1); }; return <main className='min-h-full bg-muted-background p-4 text-foreground md:p-8'><div className='mx-auto flex max-w-6xl flex-col gap-7'>
 <section className='rounded-2xl border bg-card p-6 shadow-sm md:p-9'><div className='flex flex-col gap-6 md:flex-row md:items-end md:justify-between'><div className='max-w-2xl'><span className='inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.16em] text-primary'><Mic2 className='size-3.5' /> Speaking studio</span><h1 className='mt-4 text-balance text-3xl font-bold tracking-tight md:text-4xl'>Luyện nói tự tin, từng câu một</h1><p className='mt-3 text-pretty leading-6 text-muted-foreground'>Chuẩn bị ý, ghi âm câu trả lời và tự nghe lại để cải thiện độ trôi chảy mỗi ngày.</p></div><div className='rounded-xl bg-secondary p-4'><p className='text-xs text-muted-foreground'>Tiến độ tuần này</p><p className='mt-1 text-2xl font-bold text-primary'>6 <span className='text-sm font-medium text-muted-foreground'>/ 10 bài</span></p></div></div></section>
 <section className='flex flex-col gap-4 rounded-xl border bg-card p-4 shadow-sm'><div className='flex items-center gap-2 text-sm font-semibold'><SlidersHorizontal className='size-4 text-primary' /> Chọn cách luyện tập</div><div className='flex flex-col gap-3 md:flex-row md:items-center md:justify-between'><div className='flex flex-wrap gap-2'>{speakingTypes.map((item) => <button key={item} onClick={() => choose(item)} className={cn('rounded-lg border px-3 py-2 text-sm transition-colors', type === item ? 'border-primary bg-primary text-primary-foreground' : 'bg-background text-muted-foreground hover:bg-secondary')}>{speakingTypeLabels[item]}</button>)}</div><select aria-label='Độ khó' value={difficulty} onChange={(e) => { setDifficulty(e.target.value as SpeakingDifficulty | 'all'); setPage(1); }} className='rounded-lg border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary/30'><option value='all'>Mọi độ khó</option>{speakingDifficulties.slice(1).map((x) => <option key={x}>{x}</option>)}</select></div></section>
 <div><h2 className='text-xl font-bold'>Bài luyện đề xuất</h2><p className='mt-1 text-sm text-muted-foreground'>{filtered.length} bài phù hợp với lựa chọn của bạn</p></div><div className='grid gap-4 md:grid-cols-2'>{visible.map((lesson) => <Link key={lesson.slug} href={`/speaking/${lesson.slug}`} className='group rounded-xl border bg-card p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md'><div className='flex items-start justify-between gap-3'><span className='rounded-md bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary'>{speakingTypeLabels[lesson.type]}</span><span className='text-xs text-muted-foreground'>{lesson.difficulty}</span></div><h3 className='mt-5 text-lg font-bold group-hover:text-primary'>{lesson.title}</h3><p className='mt-2 min-h-12 text-sm leading-6 text-muted-foreground'>{lesson.subtitle}</p><div className='mt-5 flex items-center justify-between border-t pt-4 text-xs text-muted-foreground'><span className='flex items-center gap-1.5'><Clock3 className='size-3.5' /> {lesson.duration} phút</span><span>Bắt đầu <ArrowRight className='ml-1 inline size-3.5 transition-transform group-hover:translate-x-1' /></span></div></Link>)}</div><div className='flex justify-center gap-2'>{Array.from({ length: pages }, (_, i) => i + 1).map((n) => <button key={n} onClick={() => setPage(n)} className={cn('size-9 rounded-lg border text-sm', page === n ? 'border-primary bg-primary text-primary-foreground' : 'bg-card text-muted-foreground hover:bg-secondary')}>{n}</button>)}</div></div></main>;
}
